// Generated by https://quicktype.io

class ExpenseModel {
  int id;
  String expenseTitle;
  num amount;
  DateTime date;

  ExpenseModel({
    required this.id,
    required this.expenseTitle,
    required this.amount,
    required this.date,
  });

  factory ExpenseModel.fromJson(Map<String, dynamic> json) {
    return ExpenseModel(
        id: json["id"],
        expenseTitle: json["expenseTitle"],
        amount: json["amount"],
        date: DateTime.parse(json["date"]));
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["id"] = id;
    data["expenseTitle"] = expenseTitle;
    data["amount"] = amount;
    data["date"] = date.toString();
    return data;
  }
}
